### ISSUE TITLE
 serverless-appsync-plugin docs showing different

### ISSUE THREAD

**Issue by himharsh1997** [davidgf/serverless-cognito#5]
According to serverless-appsync-plugin it should be in

```
provider:
  userPoolConfig:
    awsRegion: ${self:provider.region}
    defaultAction: DENY
    userPoolId: ${ssm:/demo-ms/${self:provider.stage}/MY_KEY~true} 
custom:
   appSync:
     authenticationType: AMAZON_COGNITO_USER_POOLS
     additionalAuthenticationProviders:
        - authenticationType: API_KEY
```
